services:
  php-epg:
    image: taksss/php-epg:latest
    container_name: php-epg
    # 数据持久化
    volumes:
      - ./epg/data:/htdocs/epg/data
    # 默认端口5678
    ports:
      - "5678:80"
    restart: always