name: Update Icon List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-icon-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Fetch PNG list and create iconList_default.json
        run: |
          curl -sL https://api.github.com/repos/fanmingming/live/contents/tv | jq -r '.[] | select(.name | endswith(".png")) | .name | gsub(".png$"; "")' > png_files.txt

          mkdir -p epg
          jq -R -s '
            split("\n") | map(select(length > 0)) | map({
              (gsub("[ _-]"; "") | ascii_upcase): "https://gcore.jsdelivr.net/gh/taksssss/tv/icon/\(.).png"
            }) | add' png_files.txt > epg/iconList_default.json

      - name: Clone repository
        run: |
          git clone --depth 1 --branch main https://github.com/taksssss/TVlogo.git TVlogo

      - name: Extract channel icons from markdown files
        run: |
          filter_keywords=("NEWTV" "CBN" "IHOT" "汕头")
          ignore_keywords=("CCTV")

          md_files="TVlogo/md/*.md"
          for md_file in $md_files; do
            while IFS= read -r line; do
              echo "$line" | awk -F'|' '
                {
                  for (i = 2; i <= NF; i += 2) {
                    channel_name = $i
                    match($(i + 1), /<img src="([^"]+)"/, arr)
                    image_url = arr[1]
                    if (channel_name && image_url) {
                      gsub(/https:\/\/raw.githubusercontent.com\/taksssss\/TV[lL]ogo\/.*\/img\//, "https://gcore.jsdelivr.net/gh/taksssss/tv/icon/", image_url)
                      gsub(/[ _-]/, "", channel_name)
                      channel_name = toupper(channel_name)
                      sub(/频道$/, "", channel_name)
                      printf "%s:%s\n", channel_name, image_url
                    }
                  }
                }
              ' | while IFS=: read -r channel_name image_url; do
                uppercase_channel_name=$(echo "$channel_name" | tr '[:lower:]' '[:upper:]')
                
                should_ignore=false
                for ignore_keyword in "${ignore_keywords[@]}"; do
                  uppercase_ignore_keyword=$(echo "$ignore_keyword" | tr '[:lower:]' '[:upper:]')
                  if [[ "$uppercase_channel_name" == *"$uppercase_ignore_keyword"* ]]; then
                    should_ignore=true
                    break
                  fi
                done
                
                if [ "$should_ignore" = true ]; then
                  continue
                fi

                if jq -e "has(\"$uppercase_channel_name\")" epg/iconList_default.json > /dev/null; then
                  for keyword in "${filter_keywords[@]}"; do
                    uppercase_keyword=$(echo "$keyword" | tr '[:lower:]' '[:upper:]')
                    if [[ "$uppercase_channel_name" == *"$uppercase_keyword"* ]]; then
                      jq --arg key "$uppercase_channel_name" --arg value "$image_url" \
                        '.[$key] = $value' epg/iconList_default.json > epg/iconList_default.json.tmp
                      mv epg/iconList_default.json.tmp epg/iconList_default.json
                    fi
                  done
                else
                  jq --arg key "$uppercase_channel_name" --arg value "$image_url" \
                    '.[$key] = $value' epg/iconList_default.json > epg/iconList_default.json.tmp
                  mv epg/iconList_default.json.tmp epg/iconList_default.json
                fi
              done
            done < "$md_file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add epg/iconList_default.json
          git diff --cached --quiet || git commit -m "Update iconList_default.json"
          git push
